config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :cars do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:destroy]
  get 'allmycars', to: 'cars#mycars'
  get 'allmybookings', to: 'bookings#my_bookings'
  patch 'bookings/:id/accept', to: 'bookings#accept', as: :accept
  patch 'bookings/:id/decline', to: 'bookings#decline',  as: :decline
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :user
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  validates :brand, :price_per_day, :localisation, :immatriculation, :details, :model, :photos,  presence: true
  validates :photos, length: { minimum: 2, message: "Must be many" }
  has_many :bookings, dependent: :destroy
  has_many_attached :photos


  private

  def validates_number

  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cars, dependent: :destroy
  has_many :bookings, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(bookings_params)
    @user = current_user
    @booking.car = @car
    @booking.user = @user
    if @booking.save!
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to allmybookings_path, notice: 'Bookings was successfully canceled.'
  end

  def my_bookings
    @bookings_i_want = Booking.where(user:current_user)
    @my_cars = Car.where(user:current_user)
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "Accept"
    if @booking.save
      redirect_to allmybookings_path
    end
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.status = "Decline"
    if @booking.save
      redirect_to allmybookings_path
    end
  end

  private

  def bookings_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show ]

  def index
    # @cars = Car.where(user: !current_user) ?
    @cars = Car.where.not(user: current_user)
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
    @bookings = @car.bookings
    @bookings_dates = @bookings.map do |booking|
      {
        from: booking.start_date,
        to:   booking.end_date
      }
    end
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
  end

  def mycars
    @cars = Car.where(user:current_user)
  end

  private

  def car_params
    params.require(:car).permit(:brand, :price_per_day, :localisation, :immatriculation, :details, :model, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/my_bookings.html.erb
<h1 class="title-index">MES RESERVATIONS</h1>


<div class="container_my_cars">

  <div class="container_my_car">

    <h2>Mes demandes de location ❤️ </h2>

    <div class="cards_my_cars">

    <% @bookings_i_want.each do |booking| %>
      <div class="item my_cars">
      <%= link_to car_path(booking.car), class:"link_to" do %>
        <%= cl_image_tag booking.car.photos[0].key, crop: :fill %>
          <div class="item-text">
            <div class="item-text-wrapper">
              <p class="item-text-dek"><%= "#{booking.car.brand} #{booking.car.model}" %></p>
              <h2 class="item-text-title"><%= "Du #{booking.start_date} au #{booking.end_date}" %></h2>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>

<div class="container_my_cars">
  <div class="container_my_car">
    <h2>Mes voitures en location 💲 </h2>
    <div class="cards_my_cars">
      <% @my_cars.each do |car| %>
        <% if car.bookings != [] %>
          <% car.bookings.each do |booking| %>
          <div>
            <div class="my_cars <% if booking.status == "Accept"%>car-accepted <% elsif booking.status == "Decline"%>car-declined <%end%>">
              <%= cl_image_tag car.photos[0].key, crop: :fill %>
              <%= link_to car.brand, car_path(car), class: "link_to_custom" %>
            </div>
            <div>
              <p class="demand"><%= booking.user.name %> <%= booking.status %> <%= link_to "Accept", accept_path(booking), method: :patch, class:"btn_booking" %><%= link_to "Decline", decline_path(booking), method: :patch, class:"btn_booking" %></p>
            </div>
          </div>
              <% end %>
            <% end %>
          <% end %>
        <div class="layout_my_cars">
        </div>
    </div>
  </div>
</div>

app/views/cars/_form.html.erb
<%= simple_form_for(@car) do |f| %>
  <div class = "col-6 ">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>
   <div class = "col-6 ">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>
  <div class = "col-6 ">
    <%= f.label :price_per_day %>
    <%= f.number_field :price_per_day %>
  </div>
  <div class = "col-8 ">
    <%= f.label :immatriculation %>
    <%= f.text_field :immatriculation %>
  </div>
  <div class = "col-6 ">
    <%= f.label :localisation %>
    <%= f.text_field :localisation %>
  </div>
  <div class = "col-6 ">
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <div class = "col-12">
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>
  <div class = "col-8" >
    <%= f.button :submit, class: "btn btn-primary m-4"%>
  </div>

<% end %>

app/views/cars/edit.html.erb
<div class = "banner">
  <div class="my-custom-container py-5">
    <div class="container-form">
      <div class="row justify-content-center">
        <div class="col-12 col-lg-6">
          <h2 class="text-justify font-weight-bold mt-3">EDIT</h2>
          <%= render "form", car: @cars %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<h1 class="title-index">LES VOITURES EN LOCATION PRES DE CHEZ VOUS</h1>


<div class="container mt-5" style="margin-bottom: 50px">
  <div class="cards">
  <% @cars.each do |car| %>
   <%= link_to car_path(car), class:"link_to" do %>
      <div class="card-trip">
        <% if car.photos[0] != nil %>
          <%= cl_image_tag car.photos[0].key, height: 300, width: 400, crop: :fill %>
        <% end %>
          <div class="card-trip-infos">
            <div>
              <h2><%= "#{car.brand} #{car.model}" %></h2>
              <p><%= car.details %></p>
            </div>
            <h2 class="card-trip-pricing"><%= car.price_per_day %>€/day</h2>
            <img src="https://www.ongconseil.be/wp-content/uploads/2018/03/fg-avatar-anonymous-user-retina.png" class="card-trip-user avatar" />
          </div>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/cars/mycars.html.erb
<h1 class="title-index">MES VOITURES</h1>


<div class="container mt-5">
  <div class="cards">
  <% @cars.each do |car| %>
      <%= link_to car_path(car), class:"link_to" do %>
      <div class="card-trip">
        <% if car.photos[0] != nil %>
          <%= cl_image_tag car.photos[0].key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <img src="https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="megane rs" />
        <% end %>
          <div class="card-trip-infos">
            <div>
              <h2><%= "#{car.brand} #{car.model}" %></h2>
              <p><%= car.details %></p>
            </div>
            <h2 class="card-trip-pricing"><%= car.price_per_day %>€/day</h2>
            <img src="https://www.ongconseil.be/wp-content/uploads/2018/03/fg-avatar-anonymous-user-retina.png" class="card-trip-user avatar" />
          </div>
      </div>
      <% end  %>
    <% end %>
  </div>


</div>

app/views/cars/new.html.erb
<h1 class="title-index">LOUEZ VOTRE VOITURE</h1>


<div class="my-custom-container py-5">
  <div class="container-form">
    <div class="row justify-content-center ">
      <div class="col-12 col-lg-6">
        <h2 class="text-justify font-weight-bold mt-3">Create a new car</h2>
        <%= render 'form', cars: @cars %>
      </div>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="banner" style="height: 50vh;">
  <div class="swiper myFlipSwiper" style="width: 50vw; height: 40vh;">
    <div class="swiper-wrapper">
      <% @car.photos.each do |photo| %>
        <div class="swiper-slide">
          <%= cl_image_tag photo.key, crop: :fill %>
        </div>
      <% end %>
    </div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
    <div class="swiper-pagination"></div>
  </div>
</div>
  <div class="container">
    <% if current_user != nil %>
      <% if @car.user_id == current_user.id %>
        <div class="btn_destroy">
          <td><%= link_to('DESTROY', car_path, method: :delete, data: { confirm: 'Are you sure?' }) %></td>
        </div>
      <% end %>
    <% end %>
  </div>

<div class="show_layout">

  <div class="custom-container" >
      <h2><%= "#{@car.brand} #{@car.model}" %></h2>
      <p><%= @car.details %></p>
      <ul class="ul-style">
        <li><i class="fas fa-map"></i> <%= @car.localisation %></li>
        <li><i class="fas fa-car-side"></i> <%= @car.immatriculation %></li>
        <li><i class="fas fa-euro-sign"></i> <%= @car.price_per_day %></li>
      </ul>
  </div>

  <div class="calendar">
    <div class="container">
      <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
        <h2>Book a Car</h2>
        <%= simple_form_for [@car, @booking] do |f| %>
          <%= f.input :start_date, label: "Sélectionnez vos dates:",
                                  as: :string,
                                  required: false,
                                  input_html: { id: "range_start", class: "d-none" } %>
          <%= f.input :end_date, label: false,
                                as: :string,
                                required: false,
                                input_html: { id: "range_end", class: "d-none" } %>
          <%= f.button :submit, "Book", class: "btn btn-primary", style: "width: 310px;" %>
        <% end %>
      </div>
    </div>

    <div id="booking-form-div"
        data-bookings="<%= @bookings_dates.to_json %>">
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetARide</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>

    <%= render 'shared/navbar' %>

    <div id="page-container">

      <div id="content-wrap">
        <%= yield %>

        <p class="alert"><%= alert %></p>
      </div>


      <%= render 'shared/footer' %>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
<% if @user != nil %>
<h1 class="title-index">BONJOUR <%= @user.name.upcase %></h1>
<% end %>
    <div class="swiper mySwiper">
      <div class="swiper-wrapper">
        <div class="swiper-slide" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images5.alphacoders.com/497/thumb-1920-497825.jpg)";>
          <div class="swiper-slide-content">
            <h1>Rouler dans des voitures de légende</h1>
            <a href="#" class="btn-shop">Disponible</a>
          </div>
        </div>
        <div class="swiper-slide" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80)";>
          <div class="swiper-slide-content">
            <h1>Nos plus belles sportives</h1>
            <a href="#" class="btn-shop">Disponible</a>
          </div>
        </div>
        <div class="swiper-slide" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1507242541385-02de954f97e0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80)";>
          <div class="swiper-slide-content">
            <h1>Une envie de barouder ?</h1>
            <a href="#" class="btn-shop">Disponible</a>
          </div>
        </div>
        <div class="swiper-slide" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1508357941501-0924cf312bbd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80)";>
          <div class="swiper-slide-content">
            <h1>Tous nos deux roues</h1>
            <a href="#" class="btn-shop">Disponible</a>
          </div>
        </div>
      </div>
      <div class="swiper-button-next"></div>
      <div class="swiper-button-prev"></div>
      <div class="swiper-pagination"></div>
    </div>
  </div>

  <div class="all_cards_town container">

    <div class="cards_town" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1508050919630-b135583b29ab?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80)">
      Paris
    </div>

    <div class="cards_town" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1608651422537-da1f24fdc6fe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80)">
      Lille
    </div>

    <div class="cards_town" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1602719092282-f027126b6b74?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80">
      Lyon
    </div>

    <div class="cards_town" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1595241292896-74fc11ce599f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80)">
      Bordeaux
    </div>

    <div class="cards_town" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1566838217578-1903568a76d9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80)">
      Marseille
    </div>

    <div class="cards_town" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1585943764148-4b14ded9e20b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80)">
      Nice
    </div>

    <div class="cards_town" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1541792344043-3f5b1630e42d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80)">
      Toulouse
    </div>

    <div class="cards_town" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1565893065072-b635a3166dfb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80)">
      Brest
    </div>

    <div class="cards_town" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://media-exp1.licdn.com/dms/image/C4E1BAQFhXHJ_W7nnyQ/company-background_10000/0/1614257274865?e=2159024400&v=beta&t=mdcSBcKxSsaEWthK08MHwPe_oUU9lCivGZvscpz3LXw)">
      Grenoble
    </div>
  </div>

app/views/shared/_footer.html.erb
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="header">
    <%= link_to(image_tag("logo.png", alt: "logo du wagon", class:"logo"), root_path) %>
    <nav>
      <ul class="nav-content">
        <li><%= link_to('Louer', cars_path) %></li>
        <% if current_user != nil %>
          <li><%= link_to('Mettre en location', new_car_path)  %></li>
          <li><%= link_to('Mes Voitures', allmycars_path)  %></li>
          <li><%= link_to('Mes Réservations', allmybookings_path)  %></li>
        <% else %>
        <li><%= link_to('Devenir membre', new_user_registration_path)  %> </li>
        <% end %>
      </ul>
    </nav>
    <% if current_user == nil %>
      <%= link_to "Login", new_user_session_path , class: "btn-login"%>
    <% else %>
      <%= link_to "Log-Out", destroy_user_session_path , method: :delete, class: "btn-login"%>
    <% end %>
</div >